language: python
python:
  - 2.7
  - 3.3
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install pep8 --use-mirrors
before_script:
  - "pep8 --max-line-length=119 ."
script: nosetests
